version: '3.7'
services:
  localstack:
    image: localstack/localstack
    container_name: fp-event-scheduler-localstack
    volumes:
      - ~/docker/volumes/localstack:/tmp/localstack
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 3s
      timeout: 10s
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    ports:
      - '8000:8000'